# Generated by Django 3.2.20 on 2023-10-02 06:22

from django.db import migrations

from ...utils import update_csp


def update_csp(apps, _):
    """Update csp form-action value if a digid configuration already exists"""
    DigidConfiguration = apps.get_model("digid_eherkenning", "DigidConfiguration")

    if DigidConfiguration.objects.exists():
        digid_config = DigidConfiguration.objects.get()

        if digid_config.idp_service_entity_id:
            update_csp(digid_config, "digid")


class Migration(migrations.Migration):
    dependencies = [
        ("authentication_digid", "0001_convert_digid_setting_to_db"),
    ]

    operations = [migrations.RunPython(update_csp, migrations.RunPython.noop)]
