# Generated by Django 3.2.20 on 2023-10-03 07:06

from django.db import migrations

from ...utils import update_csp


def update_csp(apps, _):
    """Update csp form-action value if an eherkenning configuration already exists"""
    EherkenningConfiguration = apps.get_model(
        "digid_eherkenning", "EherkenningConfiguration"
    )

    if EherkenningConfiguration.objects.exists():
        eherkenning_config = EherkenningConfiguration.objects.get()

        if eherkenning_config.idp_service_entity_id:
            update_csp(eherkenning_config, "eherkenning")


class Migration(migrations.Migration):
    dependencies = [
        ("authentication_eherkenning", "0001_convert_eherkenning_setting_to_db"),
    ]

    operations = []
